feat: добавил deal rest api
AlKl1M/deal pull request #1
Opened 2024-07-19 10:16 UTC by AlKl1M

2024-07-22 18:17 UTC, gobaz095 requested changes

2024-07-22 18:17 UTC, gobaz095 commented on src/main/resources/application.yaml
> +  show-time-job-cron: ${SHOW_TIME_JOB_CRON:*/5 * * * * ?}
Копипаста:)

2024-07-22 18:17 UTC, gobaz095 commented on src/test/java/com/alkl1m/deal/service/impl/ContractorOutboxServiceImplTest.java
> +        verify(eventBusService, times(2)).publishContractor(any());
А проверить что статус записи в таблице действительно изменился?:)

2024-07-22 18:17 UTC, gobaz095 commented on src/main/java/com/alkl1m/deal/schedule/ContractorJob.java
> +        outboxService.publishNextBatchToEventBus(10);
magicnumber

2024-07-22 18:17 UTC, gobaz095 commented on src/main/java/com/alkl1m/deal/service/impl/ContractorOutboxServiceImpl.java
> +    public void publishNextBatchToEventBus(int limit) {
А где обработка случая, если у нас были например такие изменения:
1 - true успешно
2 - false ошибка
3- true успешно

Получается актуальный статус у нас true, а мы дошлем false?

2024-07-22 18:30 UTC, gobaz095 commented on src/main/java/com/alkl1m/deal/service/impl/ContractorOutboxServiceImpl.java
> +    public void publishNextBatchToEventBus(int limit) {
Вопрос снимается

2024-07-22 19:57 UTC, AlKl1M commented on src/main/java/com/alkl1m/deal/domain/entity/ContractorOutbox.java
> +    @Column(name = "idempotent_key", unique = true)
https://github.com/AlKl1M/deal/pull/1/commits/07d288a385c479d929615bde50ed20a075b2d2d1

2024-07-22 19:57 UTC, AlKl1M commented on src/main/java/com/alkl1m/deal/domain/entity/ContractorOutbox.java
> +    @Column(name = "idempotent_key", unique = true)
https://github.com/AlKl1M/deal/pull/1/commits/996e3f20d90cf4ae07b02d939832d1cb26e539f6

2024-07-22 19:57 UTC, AlKl1M commented on src/main/java/com/alkl1m/deal/service/impl/DealServiceImpl.java
> +    private ContractorOutbox createContractorOutbox(boolean isMain, String contractorId) {
https://github.com/AlKl1M/deal/pull/1/commits/996e3f20d90cf4ae07b02d939832d1cb26e539f6

2024-07-22 19:58 UTC, AlKl1M commented on pom.xml
> +        <java.compiler.source>14</java.compiler.source>
https://github.com/AlKl1M/deal/pull/1/commits/996e3f20d90cf4ae07b02d939832d1cb26e539f6

2024-07-22 19:58 UTC, AlKl1M commented on src/main/resources/application.yaml
> +  show-time-job-cron: ${SHOW_TIME_JOB_CRON:*/5 * * * * ?}
https://github.com/AlKl1M/deal/pull/1/commits/996e3f20d90cf4ae07b02d939832d1cb26e539f6

2024-07-22 19:58 UTC, AlKl1M commented on src/main/java/com/alkl1m/deal/schedule/ContractorJob.java
> +        outboxService.publishNextBatchToEventBus(10);
https://github.com/AlKl1M/deal/pull/1/commits/996e3f20d90cf4ae07b02d939832d1cb26e539f6

2024-07-22 20:09 UTC, AlKl1M commented on src/test/java/com/alkl1m/deal/service/impl/ContractorOutboxServiceImplTest.java
> +        verify(eventBusService, times(2)).publishContractor(any());
https://github.com/AlKl1M/deal/commit/637242a41266544c65c76bd5f7af5ebdcc13c818

2024-07-24 13:45 UTC, gobaz095 requested changes

2024-07-24 19:34 UTC, gobaz095 approved these changes
Можно сливать

2024-07-24 22:12 UTC, merged